name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check for required files
        run: |
          test -f augment-reset.js || (echo "augment-reset.js missing" && exit 1)
          test -f README.md || (echo "README.md missing" && exit 1) 